[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@api3/contracts/=lib/contracts/contracts/",
    "@api3/airnode-protocol-v1/contracts=lib/airnode-protocol-v1/contracts/",
    "@api3/airnode-protocol/contracts=lib/airnode/packages/airnode-protocol/contracts/",
]

viaIR = true # needed to avoid stack too deep errors while compiling ;)

# evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
